services:
    laravel.test:
        build:
            context: ./vendor/laravel/sail/runtimes/8.2
            dockerfile: Dockerfile
            args:
                WWWGROUP: 1000
        image: laravelsail/php84-composer:latest
        extra_hosts:
            - "host.docker.internal:host-gateway"
        ports:
            - "${APP_PORT:-80}:80"
            - "${VITE_PORT:-5173}:${VITE_PORT:-5173}"
        environment:
            WWWUSER: 1000
            LARAVEL_SAIL: 1
            XDEBUG_MODE: "${SAIL_XDEBUG_MODE:-off}"
            XDEBUG_CONFIG: "${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}"
            IGNITION_LOCAL_SITES_PATH: "${PWD}"
        volumes:
            - ".:/var/www/html"
        networks:
            - sail
        depends_on:
            - mysql
            - mailpit
            - redis
            - elasticsearch
            - kafka
    mysql:
        image: "mysql/mysql-server:8.0"
        ports:
            - "${FORWARD_DB_PORT:-3306}:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: "${DB_DATABASE}"
            MYSQL_USER: "${DB_USERNAME}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
            MYSQL_EXTRA_OPTIONS: "${MYSQL_EXTRA_OPTIONS}"
        volumes:
            - "sail-mysql:/var/lib/mysql"
            - "./vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh"
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - "-p${DB_PASSWORD}"
            retries: 3
            timeout: 5s
    mailpit:
        image: "axllent/mailpit:latest"
        ports:
            - "${FORWARD_MAILPIT_PORT:-1025}:1025"
            - "${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025"
        networks:
            - sail
    redis:
        image: "redis:alpine"
        ports:
            - "${FORWARD_REDIS_PORT:-6379}:6379"
        volumes:
            - "sail-redis:/data"
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s
    elasticsearch:
        image: "elasticsearch:8.11.3"
        ports:
            - "${FORWARD_ELASTICSEARCH_PORT:-9200}:9200"
            - "${FORWARD_ELASTICSEARCH_TRANSPORT_PORT:-9300}:9300"
        environment:
            discovery.type: single-node
            xpack.security.enabled: false
            ES_JAVA_OPTS: "-Xms512m -Xmx512m"
        volumes:
            - "sail-elasticsearch:/usr/share/elasticsearch/data"
        networks:
            - sail
        healthcheck:
            test:
                - CMD-SHELL
                - "curl -f http://localhost:9200 || exit 1"
            retries: 3
            timeout: 30s
            interval: 30s
    phpmyadmin:
        image: "phpmyadmin/phpmyadmin:latest"
        ports:
            - "${FORWARD_PHPMYADMIN_PORT:-8080}:80"
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
        networks:
            - sail
        depends_on:
            - mysql
    redis-commander:
        image: "rediscommander/redis-commander:latest"
        ports:
            - "${FORWARD_REDIS_COMMANDER_PORT:-8081}:8081"
        environment:
            REDIS_HOSTS: local:redis:6379
        networks:
            - sail
        depends_on:
            - redis
    kibana:
        image: "kibana:8.11.3"
        ports:
            - "${FORWARD_KIBANA_PORT:-5601}:5601"
        environment:
            ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
            ELASTICSEARCH_URL: "http://elasticsearch:9200"
            XPACK_FLEET_ENABLED: "false"
            XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY: "a7a6311933d3503b89bc2dbc36572c33a6c10925682e591bffcab6911c06786d"
            XPACK_REPORTING_ENCRYPTIONKEY: "a7a6311933d3503b89bc2dbc36572c33a6c10925682e591bffcab6911c06786d"
            XPACK_SECURITY_ENCRYPTIONKEY: "a7a6311933d3503b89bc2dbc36572c33a6c10925682e591bffcab6911c06786d"
            SERVER_PUBLICBASEURL: "http://localhost:5601"
        networks:
            - sail
        depends_on:
            - elasticsearch
    zookeeper:
        image: "confluentinc/cp-zookeeper:latest"
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
        networks:
            - sail
    kafka:
        image: "confluentinc/cp-kafka:7.4.0"
        ports:
            - "${FORWARD_KAFKA_PORT:-9092}:9092"
            - "${FORWARD_KAFKA_INTERNAL_PORT:-29092}:29092"
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
            KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
            KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
            KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
        networks:
            - sail
        depends_on:
            - zookeeper
    kafka-ui:
        image: "provectuslabs/kafka-ui:latest"
        ports:
            - "${FORWARD_KAFKA_UI_PORT:-8082}:8080"
        environment:
            KAFKA_CLUSTERS_0_NAME: local
            KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
            KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
        networks:
            - sail
        depends_on:
            - kafka
networks:
    sail:
        driver: bridge
volumes:
    sail-mysql:
        driver: local
    sail-redis:
        driver: local
    sail-elasticsearch:
        driver: local
